
### /api/v1/translate/dialogue
### Принимает массив сообщений и возвращает переведённые тексты. 
### Если передать значения языковой пары, сохранится как настройки чата
### Тестировапние перевода нескольких сообщений диалога
### 1) Оператор получил сообщения в workspace, запрашиваем переводы сообщений на язык оператора RU
### 2) Оператор ответил на сообщения клиента на русском, запрашиваем переводы на арабский для отправки клиенту 

@userId = "40"
@chatId = "40"

### Перевод нескольких сообщений диалога на русский 

POST {{API_HOST}}/api/v1/translate/dialogue
Authorization: Bearer {{API_TOKEN}}
Content-Type:	application/json
X-User-Id:	{{userId}}
X-Chat-Id:	{{chatId}}

{
  "source": "consultant",
  "source_lang": "AR",
  "target_lang": "RU",
  "messages": [
    {
      "id": 2,
      "text": "مرحبا! "
    },
    {
      "id": 3,
      "text": "مسألة مالية"
    },
    {
      "id": 14,
      "text": "أهلًا يا أوليغ."
    },
    {
      "id": 18,
      "text": "أهلاً! اسمي أوليغ."
    },
    {
      "id": 5,
      "text": "address: http://google.com (test with link)"
    }
  ]
}

### Перевод нескольких сообщений опера обратно на арабский (Error)
### после перевода проверить сообщение со ссылкой id:16. ожидание: ссылка открывается
POST {{API_HOST}}/api/v1/translate/dialogue
Authorization: Bearer {{API_TOKEN}}
Content-Type:	application/json
X-User-Id:	{{userId}}
X-Chat-Id:	{{chatId}}

{
  "source": "consultant",
  "source_lang": "RU",
  "target_lang": "AR",
  "messages": [
     {
      "id": 14,
      "text": "privet, ya oleg"
    },
    {
      "id": 14,
      "text": "Приветсвую! Меня зовут Олег"
    },
    {
      "id": 15,
      "text": "Для пополнения счета воспользуйтест одним из методов оплаты: 1 2 3"
    },
    {
      "id": 16,
       "text": "[вот вам ссылка](https://www.trojmiasto.pl/tv/The-Phantom-of-the-Opera-musical-wszech-czasow-w-Trojmiescie-25-06-2026-video-109100.html)"
    },
    {
      "id": 17,
       "text": "English text. i expect it won't be translated. Для пополнения счета воспользуйтест одним из методов оплаты: 1 2 3"
    }
  ]
}


### Перевод нескольких сообщений клиента на языке не совпадающем в "source_lang": "AR"

POST {{API_HOST}}/api/v1/translate/dialogue
Authorization: Bearer {{API_TOKEN}}
Content-Type:	application/json
X-User-Id:	{{userId}}
X-Chat-Id:	{{chatId}}

{
  "source": "consultant",
  "source_lang": "AR",
  "target_lang": "RU",
  "messages": [
    {
      "id": 22,
      "text": "Hello! this is not AR language, i expect translation error!"
    },
    {
      "id": 23,
      "text": "how are you"
    }
  ]
}
