
POST {{API_HOST}}/api/v1/translate/dialogue
Authorization: Bearer {{API_TOKEN}}
Content-Type:	application/json
X-User-Id:	user1
X-Chat-Id:	chat1

{
  "source": "crm",
  "source_lang": "AR",
  "target_lang": "RU",
  "messages": [
    {
      "id": 2,
      "text": "مرحبا!"
    },
    {
      "id": 3,
      "text": "مسألة مالية"
    }
  ]
}