

GET {{API_HOST}}/api/v1/health-check?verbose=false&fresh=false
Authorization: Bearer {{API_TOKEN}}


###



GET {{API_HOST}}/api/v1/health-check?verbose=false&fresh=true
Authorization: Bearer {{API_TOKEN}}
