### Установка языковых пар AR-RU, HI-EN
### Получение списка доступных языков

@userId = "21"
@chatId = "20"

### Установка языковой пары AR-RU

POST {{API_HOST}}/api/v1/settings/lang-pair
Authorization: Bearer {{API_TOKEN}}
Content-Type:	application/json
X-User-Id:	{{{userId}}}
X-Chat-Id:	{{{{{chatId}}}}}

{
  "source_lang": "AR",
  "target_lang": "RU"
}

### Установка языковой пары HI-EN

POST {{API_HOST}}/api/v1/settings/lang-pair
Authorization: Bearer {{API_TOKEN}}
Content-Type:	application/json
X-User-Id:	{{{userId}}}
X-Chat-Id:	{{{{{chatId}}}}}

{
  "source_lang": "HI",
  "target_lang": "EN"
}

### Доступный список языков

GET {{API_HOST}}/api/v1/settings/languages
Authorization: Bearer {{API_TOKEN}}
X-User-Id:	{{{userId}}}
X-Chat-Id:	{{{{{chatId}}}}}