
@userId = "11"
@chatId = "10"

POST {{API_HOST}}/api/v1/settings/lang-pair
Authorization: Bearer {{API_TOKEN}}
Content-Type:	application/json
X-User-Id:	{{userId}}
X-Chat-Id:	{{chatId}}

{
  "source_lang": "AR",
  "target_lang": "RU"
}

### Перевод одного сообщения (почему-то ошибка 404)

POST {{API_HOST}}/api/v1/translate/message-input
Authorization: Bearer {{API_TOKEN}}
X-User-Id:	{{userId}}
X-Chat-Id:	{{chatId}}
Content-Type:	application/json

{
  "source": "consultant",
  "source_lang": "AR",
  "target_lang": "RU",
  "input_message": true,
  "messages": [
    {
      "id": 4,
      "text": "مرحبا"
    }
  ]
}