### Тест: в диалоге 2 оперетора с RU и EN языками
### 1) Запрашиваем переводы сообщений для Operator1 RU
### 2) Запрашиваем переводы сообщений для Operator2 EN

@operator_1 = "1301"
@operator_2 = "1302"
@chatId = "300"

### Перевод на RU для первого оператора

POST {{API_HOST}}/api/v1/translate/dialogue
Authorization: Bearer {{API_TOKEN}}
Content-Type:	application/json
X-User-Id:	{{operator_1}}
X-Chat-Id:	{{chatId}}

{
  "source": "consultant",
  "source_lang": "AR",
  "target_lang": "RU",
  "messages": [
    {
      "id": 2,
      "text": "مرحبا!"
    },
    {
      "id": 3,
      "text": "مسألة مالية"
    }
  ]
}

### Перевод на EN для первого оператора

POST {{API_HOST}}/api/v1/translate/dialogue
Authorization: Bearer {{API_TOKEN}}
Content-Type:	application/json
X-User-Id:	{{operator_2}}
X-Chat-Id:	{{chatId}}

{
  "source": "consultant",
  "source_lang": "AR",
  "target_lang": "EN",
  "messages": [
    {
      "id": 2,
      "text": "مرحبا!"
    },
    {
      "id": 3,
      "text": "مسألة مالية"
    }
  ]
}