### Определение языка полученного текста

@userId = "1"
@chatId = "1"

### Опеределение языка текста на русском

POST {{API_HOST}}/api/v1/settings/lang-detect
Authorization: Bearer {{API_TOKEN}}
Content-Type:	application/json
X-User-Id:	{{userId}}
X-Chat-Id:	{{chatId}}

{
  "messages": [
    {
      "id": 3,
      "text": "Определяем RU язык"
    }
  ]
}

### Опеределение языка текста на английском

POST {{API_HOST}}/api/v1/settings/lang-detect
Authorization: Bearer {{API_TOKEN}}
Content-Type:	application/json
X-User-Id:	{{userId}}
X-Chat-Id:	{{chatId}}

{
  "messages": [
    {
      "id": 3,
      "text": "Detecting EN language"
    }
  ]
}

