### Тестирование кейса, когда требуется запросить повторный перевод (клиент отредактировал текст сообщения)
### 1) Перевод первой версии сообщения
### 2) Перевод второй версии сообщения
@userId = "201"
@chatId = "200"

### Подключился оператор на языке RU, запросил перевод сообщения

POST {{API_HOST}}/api/v1/translate/dialogue
Authorization: Bearer {{API_TOKEN}}
Content-Type:	application/json
X-User-Id:	{{userId}}
X-Chat-Id:	{{chatId}}

{
  "source": "consultant",
  "source_lang": "AR",
  "target_lang": "RU",
  "messages": [
    {
      "id": 1,
      "text": "مرحبا!" 
    },
    {
      "id": 2,
      "text": "مسألة مالية" 
    }
  ]
}

### Клиент отредактировал сообщения и запрошиваем повторного перевод

POST {{API_HOST}}/api/v1/translate/dialogue
Authorization: Bearer {{API_TOKEN}}
Content-Type:	application/json
X-User-Id:	{{userId}}
X-Chat-Id:	{{chatId}}

{
  "source": "consultant",
  "source_lang": "AR",
  "target_lang": "RU",
  "messages": [
    {
      "id": 1,
      "text": "مرحبًا مرحبًا!"
    },
    {
      "id": 2,
      "text": "مسألة مالية"
    }
  ]
}